// Generated by CoffeeScript 1.7.1
(function() {
  var decodeurl, iconv, to_chinese;

  iconv = require('iconv-lite');

  to_chinese = function(buff) {
    var str, _every_is_chinese;
    _every_is_chinese = function(str) {
      var char_code, i, is_chinese, _i, _ref;
      is_chinese = true;
      for (i = _i = 0, _ref = str.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        char_code = str.charCodeAt(i);
        if (!((0 < char_code && char_code < 128) || (19968 <= char_code && char_code <= 40869))) {
          is_chinese = false;
          break;
        }
      }
      return is_chinese;
    };
    str = iconv.decode(buff, 'utf-8');
    if (_every_is_chinese(str)) {
      return str;
    }
    str = iconv.decode(buff, 'gbk');
    if (_every_is_chinese(str)) {
      return str;
    }
    return null;
  };

  module.exports = decodeurl = function(str) {
    var buff, decoded_str, hex, m, r, url_hex_parts, _i, _len;
    r = /(%[0-9A-Fa-f]{2})+/g;
    url_hex_parts = [];
    while (m = r.exec(str)) {
      url_hex_parts.push(m[0]);
    }
    for (_i = 0, _len = url_hex_parts.length; _i < _len; _i++) {
      hex = url_hex_parts[_i];
      buff = new Buffer(hex.replace(/%/g, ''), 'hex');
      decoded_str = to_chinese(buff);
      if (decoded_str) {
        str = str.replace(hex, decoded_str);
      }
    }
    return str;
  };

}).call(this);
